### ISSUE TITLE
Colab and local demo doesn't work

### ISSUE THREAD

**Issue by albiross** [adithya-s-k/VARAG#3]
Hi, i am facing the following error in both running prcedure. Thank you

2024-10-25 06:49:11.996702: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-25 06:49:12.016419: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-25 06:49:12.023220: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-25 06:49:12.038381: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-25 06:49:13.156731: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cuda
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: BAAI/bge-base-en
modules.json: 100% 349/349 [00:00<00:00, 2.25MB/s]
config_sentence_transformers.json: 100% 124/124 [00:00<00:00, 905kB/s]
README.md: 100% 90.1k/90.1k [00:00<00:00, 1.05MB/s]
sentence_bert_config.json: 100% 52.0/52.0 [00:00<00:00, 333kB/s]
config.json: 100% 719/719 [00:00<00:00, 5.15MB/s]
model.safetensors: 100% 438M/438M [00:01<00:00, 308MB/s]
tokenizer_config.json: 100% 366/366 [00:00<00:00, 2.62MB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 2.76MB/s]
tokenizer.json: 100% 711k/711k [00:00<00:00, 4.35MB/s]
special_tokens_map.json: 100% 125/125 [00:00<00:00, 1.04MB/s]
1_Pooling/config.json: 100% 190/190 [00:00<00:00, 1.57MB/s]
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cuda
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: jinaai/jina-clip-v1
modules.json: 100% 246/246 [00:00<00:00, 1.69MB/s]
config_sentence_transformers.json: 100% 205/205 [00:00<00:00, 1.50MB/s]
README.md: 100% 10.2k/10.2k [00:00<00:00, 52.5MB/s]
custom_st.py: 100% 7.49k/7.49k [00:00<00:00, 40.0MB/s]
A new version of the following files was downloaded from https://huggingface.co/jinaai/jina-clip-v1:
- custom_st.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py", line 1722, in _load_sbert_model
    module = module_class(model_name_or_path, cache_dir=cache_folder, backend=self.backend, **kwargs)
TypeError: Transformer.__init__() got an unexpected keyword argument 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/VARAG/demo.py", line 31, in <module>
    image_embedding_model = SentenceTransformer(
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py", line 306, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py", line 1724, in _load_sbert_model
    module = module_class.load(model_name_or_path)
  File "/root/.cache/huggingface/modules/transformers_modules/jinaai/jina-clip-v1/06150c7c382d7a4faedc7d5a0d8cdb59308968f4/custom_st.py", line 184, in load
    with open(sbert_config_path) as fIn:
FileNotFoundError: [Errno 2] No such file or directory: 'jinaai/jina-clip-v1/sentence_xlnet_config.json'

**Comment by SEC-sugie** [comment]
I also encountered the same error. It seems not to work with the latest version of sentence-transformers.
I tried running it using:

```
pip install sentence-transformers==3.1.1 transformers==4.45.0
```

**Comment by techthiyanes** [comment]
Script is failing due to sentence_xlnet_config.json not available inside hf hub. Please switch another clip models for generating image embeddings. Ensure that image vector dims are updated inside the class. By default it's 768.
